"""Generates app/src/main/java/com/disgusty/oldysend/ui/kit/Palettes.java.

Material Design 1 (2014) colors come from the original Material color palette (primary 500, dark 700,
accents A200/A700). Material 3 schemes are computed with the Material Color Utilities (Python port
`materialyoucolor`, spec 2021, TonalSpot variant) exactly like Flutter's ColorScheme.fromSeed, which
LocalSend uses with the seed Colors.teal.
"""
import os

from materialyoucolor.dynamiccolor.material_dynamic_colors import MaterialDynamicColors
from materialyoucolor.hct.hct import Hct
from materialyoucolor.scheme.scheme_tonal_spot import SchemeTonalSpot

# name, 500, 700, A200 (dark theme accent), A700 (light theme accent)
PALETTE = [
    ("Teal", 0x009688, 0x00796B, 0x64FFDA, 0x00BFA5),
    ("Red", 0xF44336, 0xD32F2F, 0xFF5252, 0xD50000),
    ("Pink", 0xE91E63, 0xC2185B, 0xFF4081, 0xC51162),
    ("Purple", 0x9C27B0, 0x7B1FA2, 0xE040FB, 0xAA00FF),
    ("Deep Purple", 0x673AB7, 0x512DA8, 0x7C4DFF, 0x6200EA),
    ("Indigo", 0x3F51B5, 0x303F9F, 0x536DFE, 0x304FFE),
    ("Blue", 0x2196F3, 0x1976D2, 0x448AFF, 0x2962FF),
    ("Light Blue", 0x03A9F4, 0x0288D1, 0x40C4FF, 0x0091EA),
    ("Cyan", 0x00BCD4, 0x0097A7, 0x18FFFF, 0x00B8D4),
    ("Green", 0x4CAF50, 0x388E3C, 0x69F0AE, 0x00C853),
    ("Light Green", 0x8BC34A, 0x689F38, 0xB2FF59, 0x64DD17),
    ("Lime", 0xCDDC39, 0xAFB42B, 0xEEFF41, 0xAEEA00),
    ("Yellow", 0xFFEB3B, 0xFBC02D, 0xFFFF00, 0xFFD600),
    ("Amber", 0xFFC107, 0xFFA000, 0xFFD740, 0xFFAB00),
    ("Orange", 0xFF9800, 0xF57C00, 0xFFAB40, 0xFF6D00),
    ("Deep Orange", 0xFF5722, 0xE64A19, 0xFF6E40, 0xDD2C00),
    ("Brown", 0x795548, 0x5D4037, 0xA1887F, 0x8D6E63),
    ("Blue Grey", 0x607D8B, 0x455A64, 0x90A4AE, 0x78909C),
]

ROLES = [
    "primary", "onPrimary", "primaryContainer", "onPrimaryContainer",
    "secondary", "onSecondary", "secondaryContainer", "onSecondaryContainer",
    "tertiary", "onTertiary", "tertiaryContainer", "onTertiaryContainer",
    "error", "onError", "errorContainer", "onErrorContainer",
    "surface", "onSurface", "surfaceVariant", "onSurfaceVariant",
    "outline", "outlineVariant", "inverseSurface", "inverseOnSurface", "inversePrimary",
    "surfaceDim", "surfaceBright", "surfaceContainerLowest", "surfaceContainerLow",
    "surfaceContainer", "surfaceContainerHigh", "surfaceContainerHighest", "scrim", "shadow",
]

mdc = MaterialDynamicColors(spec="2021")


def scheme(seed, dark):
    s = SchemeTonalSpot(Hct.from_int(0xFF000000 | seed), dark, 0.0, spec_version="2021")
    out = []
    for r in ROLES:
        out.append(getattr(mdc, r).get_argb(s) & 0xFFFFFFFF)
    return out


def jint(v):
    return "0x%08X" % v


lines = []
lines.append("package com.disgusty.oldysend.ui.kit;")
lines.append("")
lines.append("/** Generated by tools/gen_palettes.py — do not edit. */")
lines.append("public final class Palettes {")
lines.append("    private Palettes() {")
lines.append("    }")
lines.append("")
lines.append("    public static final String[] NAMES = {" + ", ".join('"%s"' % p[0] for p in PALETTE) + "};")
lines.append("")
lines.append("    /** Material 1: {500, 700, A200, A700} per palette entry. */")
lines.append("    public static final int[][] MD1 = {")
for p in PALETTE:
    lines.append("            {" + ", ".join(jint(0xFF000000 | c) for c in p[1:]) + "},")
lines.append("    };")
lines.append("")
for i, r in enumerate(ROLES):
    const = "".join("_" + ch if ch.isupper() else ch.upper() for ch in r)
    lines.append("    public static final int %s = %d;" % (const, i))
lines.append("    public static final int ROLE_COUNT = %d;" % len(ROLES))
lines.append("")
lines.append("    /** Material 3 TonalSpot schemes from each palette's 500 color: [entry][0=light,1=dark][role]. */")
lines.append("    public static final int[][][] MD3 = {")
for p in PALETTE:
    lines.append("            {")
    for dark in (False, True):
        vals = scheme(p[1], dark)
        lines.append("                    {" + ", ".join(jint(v) for v in vals) + "},")
    lines.append("            },")
lines.append("    };")
lines.append("}")

out = os.path.join(os.path.dirname(__file__), "..", "app", "src", "main", "java", "org", "oldysend", "ui", "kit", "Palettes.java")
os.makedirs(os.path.dirname(out), exist_ok=True)
with open(out, "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(lines) + "\n")
print("teal light primary", hex(scheme(0x009688, False)[0]), "dark", hex(scheme(0x009688, True)[0]))
