package com.disgusty.oldysend.ui.kit;

import com.disgusty.oldysend.ui.icon.IconData;

/** Icon glyphs: Material Icons (2014, used by Classic/Holo/Material 1) and Material Symbols (Material 3). */
public final class Ic {
    public final String m1;
    public final String m3;
    public final String m3Filled;

    private Ic(String m1, String m3, String m3Filled) {
        this.m1 = m1;
        this.m3 = m3;
        this.m3Filled = m3Filled;
    }

    public static final Ic SEND = new Ic(IconData.M1_SEND, IconData.M3_SEND, IconData.M3_SEND_FILLED);
    public static final Ic WIFI = new Ic(IconData.M1_WIFI, IconData.M3_WIFI, IconData.M3_WIFI_FILLED);
    public static final Ic SETTINGS = new Ic(IconData.M1_SETTINGS, IconData.M3_SETTINGS, IconData.M3_SETTINGS_FILLED);
    public static final Ic HISTORY = new Ic(IconData.M1_HISTORY, IconData.M3_HISTORY, IconData.M3_HISTORY_FILLED);
    public static final Ic INFO = new Ic(IconData.M1_INFO, IconData.M3_INFO, IconData.M3_INFO_FILLED);
    public static final Ic HELP = new Ic(IconData.M1_HELP, IconData.M3_HELP, IconData.M3_HELP_FILLED);
    public static final Ic CLOSE = new Ic(IconData.M1_CLOSE, IconData.M3_CLOSE, IconData.M3_CLOSE_FILLED);
    public static final Ic CHECK = new Ic(IconData.M1_CHECK, IconData.M3_CHECK, IconData.M3_CHECK_FILLED);
    public static final Ic ADD = new Ic(IconData.M1_ADD, IconData.M3_ADD, IconData.M3_ADD_FILLED);
    public static final Ic DELETE = new Ic(IconData.M1_DELETE, IconData.M3_DELETE, IconData.M3_DELETE_FILLED);
    public static final Ic EDIT = new Ic(IconData.M1_EDIT, IconData.M3_EDIT, IconData.M3_EDIT_FILLED);
    public static final Ic CONTENT_COPY = new Ic(IconData.M1_CONTENT_COPY, IconData.M3_CONTENT_COPY, IconData.M3_CONTENT_COPY_FILLED);
    public static final Ic CONTENT_PASTE = new Ic(IconData.M1_CONTENT_PASTE, IconData.M3_CONTENT_PASTE, IconData.M3_CONTENT_PASTE_FILLED);
    public static final Ic FOLDER = new Ic(IconData.M1_FOLDER, IconData.M3_FOLDER, IconData.M3_FOLDER_FILLED);
    public static final Ic FOLDER_OPEN = new Ic(IconData.M1_FOLDER_OPEN, IconData.M3_FOLDER_OPEN, IconData.M3_FOLDER_OPEN_FILLED);
    public static final Ic CREATE_NEW_FOLDER = new Ic(IconData.M1_CREATE_NEW_FOLDER, IconData.M3_CREATE_NEW_FOLDER, IconData.M3_CREATE_NEW_FOLDER_FILLED);
    public static final Ic INSERT_DRIVE_FILE = new Ic(IconData.M1_INSERT_DRIVE_FILE, IconData.M3_INSERT_DRIVE_FILE, IconData.M3_INSERT_DRIVE_FILE_FILLED);
    public static final Ic DESCRIPTION = new Ic(IconData.M1_DESCRIPTION, IconData.M3_DESCRIPTION, IconData.M3_DESCRIPTION_FILLED);
    public static final Ic IMAGE = new Ic(IconData.M1_IMAGE, IconData.M3_IMAGE, IconData.M3_IMAGE_FILLED);
    public static final Ic MOVIE = new Ic(IconData.M1_MOVIE, IconData.M3_MOVIE, IconData.M3_MOVIE_FILLED);
    public static final Ic AUDIOTRACK = new Ic(IconData.M1_AUDIOTRACK, IconData.M3_AUDIOTRACK, IconData.M3_AUDIOTRACK_FILLED);
    public static final Ic SUBJECT = new Ic(IconData.M1_SUBJECT, IconData.M3_SUBJECT, IconData.M3_SUBJECT_FILLED);
    public static final Ic TEXT_SNIPPET = new Ic(IconData.M1_TEXT_SNIPPET, IconData.M3_TEXT_SNIPPET, IconData.M3_TEXT_SNIPPET_FILLED);
    public static final Ic APPS = new Ic(IconData.M1_APPS, IconData.M3_APPS, IconData.M3_APPS_FILLED);
    public static final Ic ANDROID = new Ic(IconData.M1_ANDROID, IconData.M3_ANDROID, IconData.M3_ANDROID_FILLED);
    public static final Ic REFRESH = new Ic(IconData.M1_REFRESH, IconData.M3_REFRESH, IconData.M3_REFRESH_FILLED);
    public static final Ic STAR = new Ic(IconData.M1_STAR, IconData.M3_STAR, IconData.M3_STAR_FILLED);
    public static final Ic STAR_BORDER = new Ic(IconData.M1_STAR_BORDER, IconData.M3_STAR_BORDER, IconData.M3_STAR_BORDER);
    public static final Ic FAVORITE = new Ic(IconData.M1_FAVORITE, IconData.M3_FAVORITE, IconData.M3_FAVORITE_FILLED);
    public static final Ic FAVORITE_BORDER = new Ic(IconData.M1_FAVORITE_BORDER, IconData.M3_FAVORITE_BORDER, IconData.M3_FAVORITE_BORDER);
    public static final Ic MORE_VERT = new Ic(IconData.M1_MORE_VERT, IconData.M3_MORE_VERT, IconData.M3_MORE_VERT_FILLED);
    public static final Ic ARROW_BACK = new Ic(IconData.M1_ARROW_BACK, IconData.M3_ARROW_BACK, IconData.M3_ARROW_BACK_FILLED);
    public static final Ic LINK = new Ic(IconData.M1_LINK, IconData.M3_LINK, IconData.M3_LINK_FILLED);
    public static final Ic SMARTPHONE = new Ic(IconData.M1_SMARTPHONE, IconData.M3_SMARTPHONE, IconData.M3_SMARTPHONE_FILLED);
    public static final Ic COMPUTER = new Ic(IconData.M1_COMPUTER, IconData.M3_COMPUTER, IconData.M3_COMPUTER_FILLED);
    public static final Ic LANGUAGE = new Ic(IconData.M1_LANGUAGE, IconData.M3_LANGUAGE, IconData.M3_LANGUAGE_FILLED);
    public static final Ic TERMINAL = new Ic(IconData.M1_TERMINAL, IconData.M3_TERMINAL, IconData.M3_TERMINAL_FILLED);
    public static final Ic DNS = new Ic(IconData.M1_DNS, IconData.M3_DNS, IconData.M3_DNS_FILLED);
    public static final Ic LOCK = new Ic(IconData.M1_LOCK, IconData.M3_LOCK, IconData.M3_LOCK_FILLED);
    public static final Ic LOCK_OPEN = new Ic(IconData.M1_LOCK_OPEN, IconData.M3_LOCK_OPEN, IconData.M3_LOCK_OPEN_FILLED);
    public static final Ic OPEN_IN_NEW = new Ic(IconData.M1_OPEN_IN_NEW, IconData.M3_OPEN_IN_NEW, IconData.M3_OPEN_IN_NEW_FILLED);
    public static final Ic CHECK_CIRCLE = new Ic(IconData.M1_CHECK_CIRCLE, IconData.M3_CHECK_CIRCLE, IconData.M3_CHECK_CIRCLE_FILLED);
    public static final Ic ERROR = new Ic(IconData.M1_ERROR, IconData.M3_ERROR, IconData.M3_ERROR_FILLED);
    public static final Ic CANCEL = new Ic(IconData.M1_CANCEL, IconData.M3_CANCEL, IconData.M3_CANCEL_FILLED);
    public static final Ic PALETTE = new Ic(IconData.M1_PALETTE, IconData.M3_PALETTE, IconData.M3_PALETTE_FILLED);
    public static final Ic TRANSLATE = new Ic(IconData.M1_TRANSLATE, IconData.M3_TRANSLATE, IconData.M3_TRANSLATE_FILLED);
    public static final Ic ARCHIVE = new Ic(IconData.M1_ARCHIVE, IconData.M3_ARCHIVE, IconData.M3_ARCHIVE_FILLED);
    public static final Ic PICTURE_AS_PDF = new Ic(IconData.M1_PICTURE_AS_PDF, IconData.M3_PICTURE_AS_PDF, IconData.M3_PICTURE_AS_PDF_FILLED);
    public static final Ic DEVICES = new Ic(IconData.M1_DEVICES, IconData.M3_DEVICES, IconData.M3_DEVICES_FILLED);
    public static final Ic ROUTER = new Ic(IconData.M1_ROUTER, IconData.M3_ROUTER, IconData.M3_ROUTER_FILLED);
    public static final Ic TUNE = new Ic(IconData.M1_TUNE, IconData.M3_TUNE, IconData.M3_TUNE_FILLED);
    public static final Ic BUG_REPORT = new Ic(IconData.M1_BUG_REPORT, IconData.M3_BUG_REPORT, IconData.M3_BUG_REPORT_FILLED);
    public static final Ic NOTES = new Ic(IconData.M1_NOTES, IconData.M3_NOTES, IconData.M3_NOTES_FILLED);
    public static final Ic SAVE_ALT = new Ic(IconData.M1_SAVE_ALT, IconData.M3_SAVE_ALT, IconData.M3_SAVE_ALT_FILLED);
    public static final Ic ARROW_DROP_DOWN = new Ic(IconData.M1_ARROW_DROP_DOWN, IconData.M3_ARROW_DROP_DOWN, IconData.M3_ARROW_DROP_DOWN_FILLED);
    public static final Ic CHEVRON_RIGHT = new Ic(IconData.M1_CHEVRON_RIGHT, IconData.M3_CHEVRON_RIGHT, IconData.M3_CHEVRON_RIGHT_FILLED);
    public static final Ic EXPAND_MORE = new Ic(IconData.M1_EXPAND_MORE, IconData.M3_EXPAND_MORE, IconData.M3_EXPAND_MORE_FILLED);
    public static final Ic EXPAND_LESS = new Ic(IconData.M1_EXPAND_LESS, IconData.M3_EXPAND_LESS, IconData.M3_EXPAND_LESS_FILLED);
    public static final Ic PASSWORD = new Ic(IconData.M1_PASSWORD, IconData.M3_PASSWORD, IconData.M3_PASSWORD_FILLED);
    public static final Ic TIMER = new Ic(IconData.M1_TIMER, IconData.M3_TIMER, IconData.M3_TIMER_FILLED);
    public static final Ic SPEED = new Ic(IconData.M1_SPEED, IconData.M3_SPEED, IconData.M3_SPEED_FILLED);
    public static final Ic PHOTO_LIBRARY = new Ic(IconData.M1_PHOTO_LIBRARY, IconData.M3_PHOTO_LIBRARY, IconData.M3_PHOTO_LIBRARY_FILLED);
    public static final Ic SHARE = new Ic(IconData.M1_SHARE, IconData.M3_SHARE, IconData.M3_SHARE_FILLED);
    public static final Ic MENU = new Ic(IconData.M1_MENU, IconData.M3_MENU, IconData.M3_MENU_FILLED);
    public static final Ic WARNING = new Ic(IconData.M1_WARNING, IconData.M3_WARNING, IconData.M3_WARNING_FILLED);
    public static final Ic SD_STORAGE = new Ic(IconData.M1_SD_STORAGE, IconData.M3_SD_STORAGE, IconData.M3_SD_STORAGE_FILLED);
    public static final Ic CLEAR_ALL = new Ic(IconData.M1_CLEAR_ALL, IconData.M3_CLEAR_ALL, IconData.M3_CLEAR_ALL_FILLED);
    public static final Ic VISIBILITY = new Ic(IconData.M1_VISIBILITY, IconData.M3_VISIBILITY, IconData.M3_VISIBILITY_FILLED);
    public static final Ic QR_CODE = new Ic(IconData.M1_QR_CODE, IconData.M3_QR_CODE, IconData.M3_QR_CODE_FILLED);
    public static final Ic DARK_MODE = new Ic(IconData.M1_DARK_MODE, IconData.M3_DARK_MODE, IconData.M3_DARK_MODE_FILLED);
    public static final Ic BRIGHTNESS_6 = new Ic(IconData.M1_BRIGHTNESS_6, IconData.M3_BRIGHTNESS_6, IconData.M3_BRIGHTNESS_6_FILLED);
    public static final Ic RESTART_ALT = new Ic(IconData.M1_RESTART_ALT, IconData.M3_RESTART_ALT, IconData.M3_RESTART_ALT_FILLED);
    public static final Ic STOP = new Ic(IconData.M1_STOP, IconData.M3_STOP, IconData.M3_STOP_FILLED);
    public static final Ic FLASH_ON = new Ic(IconData.M1_FLASH_ON, IconData.M3_FLASH_ON, IconData.M3_FLASH_ON_FILLED);
    public static final Ic NOTIFICATIONS = new Ic(IconData.M1_NOTIFICATIONS, IconData.M3_NOTIFICATIONS, IconData.M3_NOTIFICATIONS_FILLED);
    public static final Ic SECURITY = new Ic(IconData.M1_SECURITY, IconData.M3_SECURITY, IconData.M3_SECURITY_FILLED);
    public static final Ic STORAGE = new Ic(IconData.M1_STORAGE, IconData.M3_STORAGE, IconData.M3_STORAGE_FILLED);
    public static final Ic SCHEDULE = new Ic(IconData.M1_SCHEDULE, IconData.M3_SCHEDULE, IconData.M3_SCHEDULE_FILLED);
    public static final Ic DOWNLOAD = new Ic(IconData.M1_DOWNLOAD, IconData.M3_DOWNLOAD, IconData.M3_DOWNLOAD_FILLED);
    public static final Ic UPLOAD = new Ic(IconData.M1_UPLOAD, IconData.M3_UPLOAD, IconData.M3_UPLOAD_FILLED);
    public static final Ic SELECT_ALL = new Ic(IconData.M1_SELECT_ALL, IconData.M3_SELECT_ALL, IconData.M3_SELECT_ALL_FILLED);
    public static final Ic INBOX = new Ic(IconData.M1_INBOX, IconData.M3_INBOX, IconData.M3_INBOX_FILLED);
    public static final Ic OUTBOX = new Ic(IconData.M1_OUTBOX, IconData.M3_OUTBOX, IconData.M3_OUTBOX_FILLED);
    public static final Ic SYNC = new Ic(IconData.M1_SYNC, IconData.M3_SYNC, IconData.M3_SYNC_FILLED);
    public static final Ic CODE = new Ic(IconData.M1_CODE, IconData.M3_CODE, IconData.M3_CODE_FILLED);
    public static final Ic ARROW_FORWARD = new Ic(IconData.M1_ARROW_FORWARD, IconData.M3_ARROW_FORWARD, IconData.M3_ARROW_FORWARD_FILLED);
    public static final Ic DONE_ALL = new Ic(IconData.M1_DONE_ALL, IconData.M3_DONE_ALL, IconData.M3_DONE_ALL_FILLED);
    public static final Ic VERIFIED_USER = new Ic(IconData.M1_VERIFIED_USER, IconData.M3_VERIFIED_USER, IconData.M3_VERIFIED_USER_FILLED);
    public static final Ic PLAY_ARROW = new Ic(IconData.M1_PLAY_ARROW, IconData.M3_PLAY_ARROW, IconData.M3_PLAY_ARROW_FILLED);
    public static final Ic COLOR_LENS = new Ic(IconData.M1_COLOR_LENS, IconData.M3_COLOR_LENS, IconData.M3_COLOR_LENS_FILLED);
    public static final Ic PAUSE = new Ic(IconData.M1_PAUSE, IconData.M3_PAUSE, IconData.M3_PAUSE_FILLED);
    public static final Ic KEYBOARD = new Ic(IconData.M1_KEYBOARD, IconData.M3_KEYBOARD, IconData.M3_KEYBOARD_FILLED);
}
